import type { SimulationSpec } from '../types';

/**
 * Catalog — ưu tiên lớp 12 dày (published).
 * Lớp 11 giữ seed lượng giác. Không multi-user / chia sẻ.
 */
export const SIMULATIONS: SimulationSpec[] = [
  // ─── Lớp 12: Giải tích ───────────────────────────────────────────
  {
    id: 'g12.calc.derivative-survey',
    version: '1.0.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.function-survey',
    title: 'Đạo hàm, tiếp tuyến và khảo sát hàm số',
    subtitle: 'Cát tuyến → tiếp tuyến, f & f′, cực trị, khoảng đồng/nghịch biến, BBT',
    kind: 'process-simulation',
    template: 'derivative-survey',
    dims: '2d',
    status: 'published',
    steps: 6,
    learningOutcomes: [
      'Liên hệ hệ số góc cát tuyến với định nghĩa đạo hàm',
      'Viết phương trình tiếp tuyến tại x₀',
      'Đọc cực trị và khoảng đồng/nghịch biến từ dấu f′',
      'Lập bảng biến thiên rút gọn và tìm GTLN/GTNN trên đoạn',
    ],
    prerequisites: ['Đạo hàm cơ bản', 'Đồ thị hàm số'],
    predictPrompt: 'Khi h → 0, hệ số góc cát tuyến so với hệ số góc tiếp tuyến sẽ thế nào?',
    checkpoints: [
      {
        id: 'deriv-def',
        prompt: 'f′(x₀) là giới hạn của…',
        kind: 'choice',
        answer: 'hệ số góc cát tuyến khi h → 0',
        choices: [
          'diện tích dưới đồ thị',
          'hệ số góc cát tuyến khi h → 0',
          'giá trị f(x₀)',
          'nghiệm của f(x)=0',
        ],
        explanation: 'Định nghĩa: f′(x₀) = lim [f(x₀+h)−f(x₀)]/h khi h→0 (nếu tồn tại).',
      },
      {
        id: 'deriv-sign',
        prompt: 'Trên khoảng f′ > 0 (f liên tục), hàm số…',
        kind: 'choice',
        answer: 'đồng biến',
        choices: ['nghịch biến', 'đồng biến', 'luôn dương', 'có cực đại'],
        explanation: 'Dấu đạo hàm cho chiều biến thiên: f′>0 ⇒ đồng biến (định lý đủ điều kiện).',
      },
      {
        id: 'deriv-extrema',
        prompt: 'Điểm x₀ nội tại là ứng viên cực trị khi…',
        kind: 'choice',
        answer: 'f′(x₀)=0 hoặc f′ không xác định',
        choices: [
          'f(x₀)=0',
          'f′(x₀)=0 hoặc f′ không xác định',
          'f′′(x₀)=0 bắt buộc',
          'x₀ là đầu mút đoạn',
        ],
        explanation: 'Điểm tới hạn: f′=0 hoặc f′ không xác định; cần thêm kiểm tra dấu/f′′.',
      },
    ],
    tags: ['đạo hàm', 'tiếp tuyến', 'BBT', 'cực trị', 'lớp 12'],
  },
  {
    id: 'g12.calc.antiderivative-family',
    version: '1.0.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.integral',
    title: 'Họ nguyên hàm F(x) + C',
    subtitle: 'Tích phân biến thiên, tịnh tiến họ đường cong, kiểm chứng F′ = f',
    kind: 'process-simulation',
    template: 'antiderivative-family',
    dims: '2d',
    status: 'published',
    steps: 4,
    learningOutcomes: [
      'Hiểu nguyên hàm sai khác một hằng số',
      'Dựng F bằng tích phân từ mốc x_*',
      'Nhận biết họ đường cong tịnh tiến theo Oy',
      'Kiểm chứng số F′ ≈ f',
    ],
    prerequisites: ['Đạo hàm', 'Tích phân xác định'],
    predictPrompt: 'Hai nguyên hàm của cùng f khác nhau ở điểm nào trên đồ thị?',
    checkpoints: [
      {
        id: 'anti-c',
        prompt: 'Hai nguyên hàm của cùng một f liên tục…',
        kind: 'choice',
        answer: 'khác nhau một hằng số',
        choices: [
          'trùng nhau hoàn toàn',
          'khác nhau một hằng số',
          'có đồ thị vuông góc',
          'không liên quan',
        ],
        explanation: 'Nếu F′=G′=f thì (F−G)′=0 ⇒ F−G = C.',
      },
      {
        id: 'anti-shift',
        prompt: 'Thay C trong F+C làm đồ thị…',
        kind: 'choice',
        answer: 'tịnh tiến theo phương Oy',
        choices: [
          'co giãn theo Ox',
          'tịnh tiến theo phương Oy',
          'quay quanh gốc',
          'đối xứng qua phân giác',
        ],
        explanation: 'Cộng hằng số dịch chuyển thẳng đứng.',
      },
    ],
    tags: ['nguyên hàm', 'tích phân', 'lớp 12'],
  },
  {
    id: 'g12.integral.riemann-area',
    version: '1.1.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.integral',
    title: 'Diện tích hình phẳng và tổng Riemann',
    subtitle: 'Left/mid/right, so sánh xấp xỉ với ∫|f−g|, giao điểm, sai số',
    kind: 'process-simulation',
    template: 'riemann-area',
    dims: '2d',
    status: 'published',
    steps: 4,
    learningOutcomes: [
      'Phân biệt quy tắc Riemann trái, trung điểm, phải',
      'Liên hệ tổng Riemann với diện tích miền kẹp',
      'Ước lượng sai số khi đổi n và quy tắc',
      'Xử lý giao điểm và trị tuyệt đối |f−g|',
    ],
    prerequisites: ['Tích phân xác định', 'Đồ thị hàm số'],
    predictPrompt: 'Với f lồi trên [a,b] và g=0, quy tắc nào trong left/mid/right thường “ôm” đồ thị tốt hơn?',
    checkpoints: [
      {
        id: 'riemann-n-effect',
        prompt: 'Khi n tăng (midpoint, f trơn), sai số |S_n − S| thường…',
        kind: 'choice',
        answer: 'giảm (hội tụ về tích phân)',
        choices: [
          'tăng không giới hạn',
          'giảm (hội tụ về tích phân)',
          'không đổi với mọi n',
          'luôn bằng 0 với mọi n',
        ],
        explanation: 'Tổng Riemann hội tụ về tích phân khi n→∞.',
      },
      {
        id: 'riemann-abs',
        prompt: 'Diện tích miền kẹp hai đường dùng…',
        kind: 'choice',
        answer: '|f(x) − g(x)|',
        choices: ['f+g', 'f−g không |·|', '|f(x) − g(x)|', 'f′−g′'],
        explanation: 'Diện tích ≥ 0 nên lấy trị tuyệt đối hoặc tách khoảng.',
      },
      {
        id: 'riemann-rule',
        prompt: 'Quy tắc midpoint chọn điểm mẫu trên mỗi khoảng ở…',
        kind: 'choice',
        answer: 'trung điểm khoảng',
        choices: ['đầu mút trái', 'đầu mút phải', 'trung điểm khoảng', 'ngẫu nhiên'],
        explanation: 'Left/right/mid khác nhau chỗ chọn xᵢ*.',
      },
    ],
    tags: ['riemann', 'diện tích', 'tích phân', 'lớp 12'],
  },
  {
    id: 'g12.integral.solid-revolution',
    version: '1.2.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.solid-revolution',
    title: 'Khối tròn xoay: Disk / Washer / Shell',
    subtitle: 'Ox (đĩa–vành) và Oy (vỏ trụ), 3D, Riemann vs tích phân',
    kind: 'process-simulation',
    template: 'solid-revolution',
    dims: 'hybrid',
    status: 'published',
    steps: 5,
    learningOutcomes: [
      'Phân biệt disk, washer quanh Ox và shell quanh Oy',
      'Viết V = π∫R², π∫(R²−r²) hoặc ∫2π|x|h(x)dx',
      'Chọn phương pháp theo trục quay và dạng miền',
      'So sánh tổng lát/vỏ với tích phân',
    ],
    prerequisites: ['Tích phân', 'Diện tích hình tròn'],
    predictPrompt: 'Quay miền dưới y=x (0≤x≤1) quanh Oy — shell hay disk theo y tiện hơn?',
    checkpoints: [
      {
        id: 'disk-formula',
        prompt: 'Disk quanh Ox của y=f(x)≥0:',
        kind: 'choice',
        answer: 'π ∫_a^b [f(x)]² dx',
        choices: ['∫f', 'π∫f', 'π ∫_a^b [f(x)]² dx', '2π∫x f'],
        explanation: 'A(x)=πR² với R=f(x).',
      },
      {
        id: 'shell-formula',
        prompt: 'Shell quanh Oy, miền 0≤y≤f(x), a≤x≤b:',
        kind: 'choice',
        answer: '∫ 2π x f(x) dx (x≥0)',
        choices: [
          'π∫[f]² dx',
          '∫ 2π x f(x) dx (x≥0)',
          '∫ f(x) dx',
          '2π∫ f(x) dx',
        ],
        explanation: 'Vỏ trụ: bán kính x, chiều cao f, “diện tích” 2πx f.',
      },
      {
        id: 'washer-vs-disk',
        prompt: 'Washer khác disk vì…',
        kind: 'choice',
        answer: 'trừ lỗ trong (R² − r²)',
        choices: ['đổi trục Oy', 'trừ lỗ trong (R² − r²)', 'không tích phân', 'chỉ hàm bậc nhất'],
        explanation: 'A=π(R²−r²).',
      },
      {
        id: 'solid-scale',
        prompt: 'Disk: R nhân 2 (mọi x) thì V…',
        kind: 'choice',
        answer: 'nhân 4',
        choices: ['nhân 2', 'nhân 4', 'không đổi', 'chia 2'],
        explanation: 'V tỉ lệ R².',
      },
    ],
    tags: ['khối tròn xoay', 'disk', 'washer', 'shell', 'Oy', '3D', 'lớp 12'],
  },
  {
    id: 'g12.calc.rational-asymptote',
    version: '1.0.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.function-survey',
    title: 'Hàm hữu tỉ: tiệm cận đứng, ngang, xiên',
    subtitle: 'P/Q, hố, hành vi vô cùng, dấu f′, cực trị — khảo sát chi tiết',
    kind: 'process-simulation',
    template: 'rational-asymptote',
    dims: '2d',
    status: 'published',
    steps: 6,
    learningOutcomes: [
      'Phân biệt TC đứng và hố (gián đoạn khử)',
      'Nhận TC ngang / xiên theo hành vi vô cùng',
      'Đọc đồ thị gần các đường tiệm cận',
      'Tìm cực trị số trên các khoảng xác định',
    ],
    prerequisites: ['Phân thức hữu tỉ', 'Đạo hàm', 'Giới hạn'],
    predictPrompt: 'f=(x²+1)/(x−1) có tiệm cận loại nào khi x→±∞?',
    checkpoints: [
      {
        id: 'rat-vert',
        prompt: 'Q(x₀)=0, P(x₀)≠0 (đã rút gọn) ⇒',
        kind: 'choice',
        answer: 'tiệm cận đứng x=x₀',
        choices: ['tiệm cận ngang', 'tiệm cận đứng x=x₀', 'hố tại x₀', 'cực tiểu'],
        explanation: 'Mẫu triệt tiêu, tử khác 0 → |f|→∞.',
      },
      {
        id: 'rat-hole',
        prompt: 'P và Q cùng triệt tiêu tại x₀ (nhân tử chung) thường là…',
        kind: 'choice',
        answer: 'hố (gián đoạn khử được)',
        choices: ['TC đứng bắt buộc', 'hố (gián đoạn khử được)', 'TC xiên', 'không xác định miền'],
        explanation: 'Rút gọn được → lỗ trên đồ thị, có thể khử.',
      },
      {
        id: 'rat-oblique',
        prompt: 'deg P = deg Q + 1 thường dẫn tới…',
        kind: 'choice',
        answer: 'tiệm cận xiên',
        choices: ['y=0', 'tiệm cận xiên', 'không có TC', 'chỉ TC đứng'],
        explanation: 'Chia đa thức được y=mx+c + phần dư/mẫu.',
      },
    ],
    tags: ['hữu tỉ', 'tiệm cận', 'khảo sát', 'lớp 12'],
  },
  {
    id: 'g12.stat.descriptive',
    version: '1.0.0',
    grade: 12,
    strand: 'statistics',
    topicCode: 'g12.statistics.descriptive',
    title: 'Thống kê mô tả: mẫu, ghép nhóm, ngoại lệ',
    subtitle: 'Mean, median, IQR, s², histogram, kéo điểm, so ghép nhóm',
    kind: 'exploration-lab',
    template: 'statistics-lab',
    dims: '2d',
    status: 'published',
    steps: 5,
    learningOutcomes: [
      'Tính và giải thích mean, median, mode, tứ phân vị',
      'Tính phương sai mẫu và độ lệch chuẩn',
      'Nhận ngoại lệ theo quy tắc 1.5×IQR',
      'Lập bảng tần số ghép nhóm và so mean ghép nhóm với mean thô',
    ],
    prerequisites: ['Trung bình, tần số', 'Căn bậc hai'],
    predictPrompt: 'Thêm một giá trị rất lớn vào mẫu — mean hay median lệch mạnh hơn?',
    checkpoints: [
      {
        id: 'stat-mean-med',
        prompt: 'Ngoại lệ lớn thường ảnh hưởng…',
        kind: 'choice',
        answer: 'mean nhiều hơn median',
        choices: ['median nhiều hơn mean', 'mean nhiều hơn median', 'IQR nhiều nhất', 'mode luôn đổi'],
        explanation: 'Mean dùng mọi giá trị; median chỉ thứ tự.',
      },
      {
        id: 'stat-var',
        prompt: 'Phương sai mẫu s² thường chia cho…',
        kind: 'choice',
        answer: 'n − 1',
        choices: ['n', 'n − 1', 'n + 1', '2n'],
        explanation: 'Hiệu chỉnh Bessel cho ước lượng không thiên vị.',
      },
      {
        id: 'stat-outlier',
        prompt: 'Hàng rào ngoại lệ phổ biến:',
        kind: 'choice',
        answer: 'Q1 − 1.5·IQR và Q3 + 1.5·IQR',
        choices: [
          'mean ± s',
          'Q1 − 1.5·IQR và Q3 + 1.5·IQR',
          'min và max',
          'median ± IQR',
        ],
        explanation: 'Quy tắc Tukey 1.5×IQR.',
      },
    ],
    tags: ['thống kê', 'histogram', 'phương sai', 'lớp 12'],
  },
  {
    id: 'g12.integral.cross-section',
    version: '1.1.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.integral',
    title: 'Thể tích theo thiết diện song song',
    subtitle: 'V=∫S(x)dx — lát vuông, tròn, tam giác, chữ nhật',
    kind: 'process-simulation',
    template: 'cross-section',
    dims: 'hybrid',
    status: 'published',
    steps: 4,
    learningOutcomes: [
      'Viết S(x) theo dạng lát cắt',
      'Xấp xỉ thể tích bằng tổng lát mỏng',
      'Liên hệ với tích phân ∫S',
    ],
    prerequisites: ['Tích phân', 'Diện tích đa giác/tròn'],
    predictPrompt: 'Lát cắt vuông cạnh s(x) thì S(x) bằng gì?',
    checkpoints: [
      {
        id: 'cross-square',
        prompt: 'Vuông cạnh s(x) có diện tích…',
        kind: 'choice',
        answer: '[s(x)]²',
        choices: ['s(x)', '[s(x)]²', 'π[s(x)]²', 's/2'],
        explanation: 'S=a².',
      },
      {
        id: 'cross-circle',
        prompt: 'Lát tròn đường kính s(x) có…',
        kind: 'choice',
        answer: 'π[s(x)/2]²',
        choices: ['π[s]²', 'π[s(x)/2]²', 's²', '2πs'],
        explanation: 'Bán kính s/2.',
      },
    ],
    tags: ['thiết diện', 'thể tích', 'lớp 12'],
  },

  // ─── Lớp 12: Hình học tọa độ ─────────────────────────────────────
  {
    id: 'g12.geom.space-coords',
    version: '1.0.0',
    grade: 12,
    strand: 'geometry',
    topicCode: 'g12.geometry.space-coords',
    title: 'Tọa độ Oxyz: đường, mặt phẳng, mặt cầu',
    subtitle: '3D tương tác — khoảng cách, góc, giao mp ∩ cầu, trong/ngoài cầu',
    kind: 'process-simulation',
    template: 'space-coords',
    dims: '3d',
    status: 'published',
    steps: 6,
    learningOutcomes: [
      'Viết PT tham số đường thẳng và PT mặt phẳng',
      'Viết PT mặt cầu; phân loại điểm so với cầu',
      'Tính d(điểm, mp) và d(I, mp)',
      'Phân loại mp ∩ cầu: không giao / tiếp / cắt (đường tròn)',
      'Tính góc giữa đường thẳng và mặt phẳng',
    ],
    prerequisites: ['Vectơ trong không gian', 'Tích vô hướng'],
    predictPrompt: 'Khi d(I, mp) < R, giao của mặt phẳng và mặt cầu là hình gì?',
    checkpoints: [
      {
        id: 'space-plane',
        prompt: 'Mặt phẳng với pháp tuyến n qua P có dạng…',
        kind: 'choice',
        answer: 'n · (M − P) = 0',
        choices: ['n × (M−P)=0', 'n · (M − P) = 0', '|M−P|=R', 'M = P + t n'],
        explanation: 'Mọi vector trong mp vuông góc pháp tuyến.',
      },
      {
        id: 'space-sphere-cut',
        prompt: 'd(I,mp) < R thì mp và cầu…',
        kind: 'choice',
        answer: 'cắt nhau theo đường tròn',
        choices: ['không giao', 'tiếp xúc một điểm', 'cắt nhau theo đường tròn', 'trùng nhau'],
        explanation: 'Bán kính giao r = √(R²−d²).',
      },
      {
        id: 'space-angle',
        prompt: 'sinθ (góc đường–mp) bằng…',
        kind: 'choice',
        answer: '|u·n| / (|u||n|)',
        choices: ['|u·n| / (|u||n|)', 'u·n', '|u×n|', '1'],
        explanation: 'θ góc đường–mp: sinθ = |cos(góc u, n)|.',
      },
    ],
    tags: ['Oxyz', 'mặt cầu', 'mặt phẳng', '3D', 'lớp 12'],
  },

  // ─── Lớp 12: Xác suất ────────────────────────────────────────────
  {
    id: 'g12.prob.bayes',
    version: '1.0.0',
    grade: 12,
    strand: 'probability',
    topicCode: 'g12.probability.bayes',
    title: 'Xác suất có điều kiện và định lý Bayes',
    subtitle: 'Cây XS, bảng 1000 người, TP/FP, PPV — chống bẫy trực giác',
    kind: 'exploration-lab',
    template: 'bayes-lab',
    dims: '2d',
    status: 'published',
    steps: 5,
    learningOutcomes: [
      'Phân biệt P(+|B) và P(B|+)',
      'Dùng xác suất toàn phần tính P(+)',
      'Áp dụng Bayes; đọc PPV từ TP/(TP+FP)',
      'Nhận ra vai trò của prior khi bệnh hiếm',
    ],
    prerequisites: ['Xác suất có điều kiện', 'Công thức nhân'],
    predictPrompt: 'Bệnh 1%, độ nhạy 99%, độ đặc hiệu 95%. Dương tính → P(bệnh|+) khoảng bao nhiêu %?',
    checkpoints: [
      {
        id: 'bayes-swap',
        prompt: 'P(+|B) và P(B|+)…',
        kind: 'choice',
        answer: 'nói chung khác nhau',
        choices: ['luôn bằng nhau', 'nói chung khác nhau', 'tổng bằng 1', 'không xác định'],
        explanation: 'Đó là hai điều kiện ngược chiều; Bayes chuyển từ cái này sang cái kia.',
      },
      {
        id: 'bayes-ppv',
        prompt: 'P(B|+) xấp xỉ trên bảng đếm bằng…',
        kind: 'choice',
        answer: 'TP / (TP + FP)',
        choices: ['TP/population', 'TP / (TP + FP)', 'độ nhạy', 'độ đặc hiệu'],
        explanation: 'Trong nhóm dương tính, tỉ lệ bệnh thật là TP/(TP+FP).',
      },
      {
        id: 'bayes-rare',
        prompt: 'Bệnh rất hiếm, xét nghiệm tốt — P(B|+) thường…',
        kind: 'choice',
        answer: 'thấp hơn trực giác (do FP)',
        choices: [
          'gần 100%',
          'thấp hơn trực giác (do FP)',
          'bằng độ nhạy',
          'bằng prior',
        ],
        explanation: 'Dương tính giả từ đa số người khỏe có thể át dương tính thật.',
      },
    ],
    tags: ['Bayes', 'xác suất', 'PPV', 'lớp 12'],
  },

  // ─── Lớp 11 seed (giữ, không phải trọng tâm đợt này) ─────────────
  {
    id: 'g11.trig.unit-circle',
    version: '1.1.0',
    grade: 11,
    strand: 'trigonometry',
    topicCode: 'g11.trig.unit-circle',
    title: 'Đường tròn lượng giác và đồ thị sóng',
    subtitle: 'Unit circle ↔ sin/cos/tan/cot · biên độ · tần số · pha',
    kind: 'interactive-model',
    template: 'unit-circle-trig',
    dims: '2d',
    status: 'published',
    steps: 1,
    learningOutcomes: [
      'Đọc sin, cos trên đường tròn đơn vị',
      'Liên hệ góc với đồ thị sóng',
      'Nhận tiệm cận tan/cot',
    ],
    prerequisites: ['Góc và radian'],
    predictPrompt: 'Sin hoàn thành mấy chu kỳ trên [0, 2π]?',
    checkpoints: [
      {
        id: 'trig-sin-cos-point',
        prompt: 'Điểm góc θ trên đường tròn đơn vị:',
        kind: 'choice',
        answer: '(cos θ, sin θ)',
        choices: ['(sin θ, cos θ)', '(cos θ, sin θ)', '(tan θ, cot θ)', '(θ, sin θ)'],
        explanation: 'x=cosθ, y=sinθ.',
      },
      {
        id: 'trig-period-sin',
        prompt: 'Chu kỳ cơ bản của sin:',
        kind: 'choice',
        answer: '2π',
        choices: ['π/2', 'π', '2π', '4π'],
        explanation: 'sin(θ+2π)=sinθ.',
      },
    ],
    tags: ['lượng giác', 'lớp 11'],
  },
];

export function getSimulation(id: string): SimulationSpec | undefined {
  return SIMULATIONS.find((item) => item.id === id);
}

export function listSimulations(filter?: {
  grade?: number | 'all';
  strand?: string | 'all';
  query?: string;
  status?: 'all' | 'published' | 'draft';
}): SimulationSpec[] {
  const grade = filter?.grade ?? 'all';
  const strand = filter?.strand ?? 'all';
  const query = (filter?.query ?? '').trim().toLowerCase();
  const status = filter?.status ?? 'all';

  return SIMULATIONS.filter((item) => {
    if (grade !== 'all' && item.grade !== grade) return false;
    if (strand !== 'all' && item.strand !== strand) return false;
    if (status !== 'all' && item.status !== status) return false;
    if (!query) return true;
    const hay = [item.title, item.subtitle, item.topicCode, ...item.tags, ...item.learningOutcomes].join(' ').toLowerCase();
    return hay.includes(query);
  }).sort((a, b) => b.grade - a.grade || a.title.localeCompare(b.title, 'vi'));
}
