import type { SimulationSpec } from '../types';
import { applyG12ToolTrip } from './g12ToolTrip';

/**
 * Catalog — lớp 12 + lớp 11 dày (published).
 * Không multi-user / chia sẻ. GeoGebra Lab tách riêng.
 * Meta tool-trip G12: applyG12ToolTrip (stepMissions + unlockAtStep).
 */
export const SIMULATIONS: SimulationSpec[] = [
  // ─── Lớp 12: Giải tích ───────────────────────────────────────────
  {
    id: 'g12.calc.derivative-survey',
    version: '1.0.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.function-survey',
    title: 'Đạo hàm, tiếp tuyến và khảo sát hàm số',
    subtitle: 'Cát tuyến đến tiếp tuyến, $f$ và $f^{\\prime}$, cực trị, khoảng đồng/nghịch biến, BBT',
    kind: 'process-simulation',
    template: 'derivative-survey',
    dims: '2d',
    status: 'published',
    steps: 6,
    learningOutcomes: [
      'Liên hệ hệ số góc cát tuyến với định nghĩa đạo hàm',
      'Viết phương trình tiếp tuyến tại $x_0$',
      'Đọc cực trị và khoảng đồng/nghịch biến từ dấu $f^{\\prime}$',
      'Lập bảng biến thiên rút gọn và tìm GTLN/GTNN trên đoạn',
    ],
    prerequisites: ['Đạo hàm cơ bản', 'Đồ thị hàm số'],
    predictPrompt: 'Khi $h \\to 0$, hệ số góc cát tuyến so với hệ số góc tiếp tuyến sẽ thế nào?',
    checkpoints: [
      {
        id: 'deriv-def',
        prompt: '$f^{\\prime}(x_0)$ là giới hạn của…',
        kind: 'choice',
        answer: 'hệ số góc cát tuyến khi $h \\to 0$',
        choices: [
          'diện tích dưới đồ thị',
          'hệ số góc cát tuyến khi $h \\to 0$',
          'giá trị $f(x_0)$',
          'nghiệm của $f(x)=0$',
        ],
        explanation: 'Định nghĩa: $f^{\\prime}(x_0)=\\lim_{h\\to0}\\dfrac{f(x_0+h)-f(x_0)}{h}$ khi giới hạn tồn tại.',
      },
      {
        id: 'deriv-sign',
        prompt: 'Trên khoảng $f^{\\prime}>0$ với $f$ liên tục, hàm số…',
        kind: 'choice',
        answer: 'đồng biến',
        choices: ['nghịch biến', 'đồng biến', 'luôn dương', 'có cực đại'],
        explanation: 'Dấu đạo hàm cho chiều biến thiên: $f^{\\prime}>0 \\Rightarrow f$ đồng biến.',
      },
      {
        id: 'deriv-extrema',
        prompt: 'Điểm $x_0$ nội tại là ứng viên cực trị khi…',
        kind: 'choice',
        answer: '$f^{\\prime}(x_0)=0$ hoặc $f^{\\prime}$ không xác định',
        choices: [
          '$f(x_0)=0$',
          '$f^{\\prime}(x_0)=0$ hoặc $f^{\\prime}$ không xác định',
          '$f^{\\prime\\prime}(x_0)=0$ bắt buộc',
          '$x_0$ là đầu mút đoạn',
        ],
        explanation: 'Điểm tới hạn thỏa $f^{\\prime}=0$ hoặc $f^{\\prime}$ không xác định; cần kiểm tra thêm dấu đạo hàm.',
      },
    ],
    tags: ['đạo hàm', 'tiếp tuyến', 'BBT', 'cực trị', 'lớp 12'],
  },
  {
    id: 'g12.calc.antiderivative-family',
    version: '1.0.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.integral',
    title: 'Họ nguyên hàm $F(x)+C$',
    subtitle: 'Tích phân biến thiên, tịnh tiến họ đường cong, kiểm chứng $F^{\\prime}=f$',
    kind: 'process-simulation',
    template: 'antiderivative-family',
    dims: '2d',
    status: 'published',
    steps: 4,
    learningOutcomes: [
      'Hiểu nguyên hàm sai khác một hằng số',
      'Dựng $F$ bằng tích phân từ mốc $x_*$',
      'Nhận biết họ đường cong tịnh tiến theo $Oy$',
      'Kiểm chứng số $F^{\\prime}\\approx f$',
    ],
    prerequisites: ['Đạo hàm', 'Tích phân xác định'],
    predictPrompt: 'Hai nguyên hàm của cùng f khác nhau ở điểm nào trên đồ thị?',
    checkpoints: [
      {
        id: 'anti-c',
        prompt: 'Hai nguyên hàm của cùng một f liên tục…',
        kind: 'choice',
        answer: 'khác nhau một hằng số',
        choices: [
          'trùng nhau hoàn toàn',
          'khác nhau một hằng số',
          'có đồ thị vuông góc',
          'không liên quan',
        ],
        explanation: 'Nếu F′=G′=f thì (F−G)′=0 ⇒ F−G = C.',
      },
      {
        id: 'anti-shift',
        prompt: 'Thay C trong F+C làm đồ thị…',
        kind: 'choice',
        answer: 'tịnh tiến theo phương Oy',
        choices: [
          'co giãn theo Ox',
          'tịnh tiến theo phương Oy',
          'quay quanh gốc',
          'đối xứng qua phân giác',
        ],
        explanation: 'Cộng hằng số dịch chuyển thẳng đứng.',
      },
    ],
    tags: ['nguyên hàm', 'tích phân', 'lớp 12'],
  },
  {
    id: 'g12.integral.riemann-area',
    version: '1.1.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.integral',
    title: 'Diện tích hình phẳng và tổng Riemann',
    subtitle: 'Left/mid/right, so sánh xấp xỉ với $\\int |f-g|$, giao điểm và sai số',
    kind: 'process-simulation',
    template: 'riemann-area',
    dims: '2d',
    status: 'published',
    steps: 4,
    learningOutcomes: [
      'Phân biệt quy tắc Riemann trái, trung điểm, phải',
      'Liên hệ tổng Riemann với diện tích miền kẹp',
      'Ước lượng sai số khi đổi n và quy tắc',
      'Xử lý giao điểm và trị tuyệt đối |f−g|',
    ],
    prerequisites: ['Tích phân xác định', 'Đồ thị hàm số'],
    predictPrompt: 'Với f lồi trên [a,b] và g=0, quy tắc nào trong left/mid/right thường “ôm” đồ thị tốt hơn?',
    checkpoints: [
      {
        id: 'riemann-n-effect',
        prompt: 'Khi n tăng (midpoint, f trơn), sai số |S_n − S| thường…',
        kind: 'choice',
        answer: 'giảm (hội tụ về tích phân)',
        choices: [
          'tăng không giới hạn',
          'giảm (hội tụ về tích phân)',
          'không đổi với mọi n',
          'luôn bằng 0 với mọi n',
        ],
        explanation: 'Tổng Riemann hội tụ về tích phân khi n→∞.',
      },
      {
        id: 'riemann-abs',
        prompt: 'Diện tích miền kẹp hai đường dùng…',
        kind: 'choice',
        answer: '|f(x) − g(x)|',
        choices: ['f+g', 'f−g không |·|', '|f(x) − g(x)|', 'f′−g′'],
        explanation: 'Diện tích ≥ 0 nên lấy trị tuyệt đối hoặc tách khoảng.',
      },
      {
        id: 'riemann-rule',
        prompt: 'Quy tắc midpoint chọn điểm mẫu trên mỗi khoảng ở…',
        kind: 'choice',
        answer: 'trung điểm khoảng',
        choices: ['đầu mút trái', 'đầu mút phải', 'trung điểm khoảng', 'ngẫu nhiên'],
        explanation: 'Left/right/mid khác nhau chỗ chọn xᵢ*.',
      },
    ],
    tags: ['riemann', 'diện tích', 'tích phân', 'lớp 12'],
  },
  {
    id: 'g12.integral.solid-revolution',
    version: '1.2.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.solid-revolution',
    title: 'Khối tròn xoay: Disk / Washer / Shell',
    subtitle: 'Ox (đĩa–vành) và Oy (vỏ trụ), 3D, Riemann vs tích phân',
    kind: 'process-simulation',
    template: 'solid-revolution',
    dims: 'hybrid',
    status: 'published',
    steps: 5,
    learningOutcomes: [
      'Phân biệt disk, washer quanh Ox và shell quanh Oy',
      'Viết $V=\\pi\\int R^2$, $V=\\pi\\int(R^2-r^2)$ hoặc $V=\\int 2\\pi|x|h(x)\\,dx$',
      'Chọn phương pháp theo trục quay và dạng miền',
      'So sánh tổng lát/vỏ với tích phân',
    ],
    prerequisites: ['Tích phân', 'Diện tích hình tròn'],
    predictPrompt: 'Quay miền dưới $y=x$, $0\\le x\\le1$ quanh $Oy$: shell hay disk theo $y$ tiện hơn?',
    checkpoints: [
      {
        id: 'disk-formula',
        prompt: 'Disk quanh Ox của y=f(x)≥0:',
        kind: 'choice',
        answer: 'π ∫_a^b [f(x)]² dx',
        choices: ['∫f', 'π∫f', 'π ∫_a^b [f(x)]² dx', '2π∫x f'],
        explanation: 'A(x)=πR² với R=f(x).',
      },
      {
        id: 'shell-formula',
        prompt: 'Shell quanh Oy, miền 0≤y≤f(x), a≤x≤b:',
        kind: 'choice',
        answer: '∫ 2π x f(x) dx (x≥0)',
        choices: [
          'π∫[f]² dx',
          '∫ 2π x f(x) dx (x≥0)',
          '∫ f(x) dx',
          '2π∫ f(x) dx',
        ],
        explanation: 'Vỏ trụ: bán kính x, chiều cao f, “diện tích” 2πx f.',
      },
      {
        id: 'washer-vs-disk',
        prompt: 'Washer khác disk vì…',
        kind: 'choice',
        answer: 'trừ lỗ trong (R² − r²)',
        choices: ['đổi trục Oy', 'trừ lỗ trong (R² − r²)', 'không tích phân', 'chỉ hàm bậc nhất'],
        explanation: 'A=π(R²−r²).',
      },
      {
        id: 'solid-scale',
        prompt: 'Disk: R nhân 2 (mọi x) thì V…',
        kind: 'choice',
        answer: 'nhân 4',
        choices: ['nhân 2', 'nhân 4', 'không đổi', 'chia 2'],
        explanation: 'V tỉ lệ R².',
      },
    ],
    tags: ['khối tròn xoay', 'disk', 'washer', 'shell', 'Oy', '3D', 'lớp 12'],
  },
  {
    id: 'g12.calc.rational-asymptote',
    version: '1.0.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.function-survey',
    title: 'Hàm hữu tỉ: tiệm cận đứng, ngang, xiên',
    subtitle: '$P/Q$, hố, hành vi vô cùng, dấu $f^{\\prime}$ và cực trị',
    kind: 'process-simulation',
    template: 'rational-asymptote',
    dims: '2d',
    status: 'published',
    steps: 6,
    learningOutcomes: [
      'Phân biệt TC đứng và hố (gián đoạn khử)',
      'Nhận TC ngang / xiên theo hành vi vô cùng',
      'Đọc đồ thị gần các đường tiệm cận',
      'Tìm cực trị số trên các khoảng xác định',
    ],
    prerequisites: ['Phân thức hữu tỉ', 'Đạo hàm', 'Giới hạn'],
    predictPrompt: '$f(x)=\\dfrac{x^2+1}{x-1}$ có tiệm cận loại nào khi $x\\to\\pm\\infty$?',
    checkpoints: [
      {
        id: 'rat-vert',
        prompt: 'Q(x₀)=0, P(x₀)≠0 (đã rút gọn) ⇒',
        kind: 'choice',
        answer: 'tiệm cận đứng x=x₀',
        choices: ['tiệm cận ngang', 'tiệm cận đứng x=x₀', 'hố tại x₀', 'cực tiểu'],
        explanation: 'Mẫu triệt tiêu, tử khác 0 → |f|→∞.',
      },
      {
        id: 'rat-hole',
        prompt: 'P và Q cùng triệt tiêu tại x₀ (nhân tử chung) thường là…',
        kind: 'choice',
        answer: 'hố (gián đoạn khử được)',
        choices: ['TC đứng bắt buộc', 'hố (gián đoạn khử được)', 'TC xiên', 'không xác định miền'],
        explanation: 'Rút gọn được → lỗ trên đồ thị, có thể khử.',
      },
      {
        id: 'rat-oblique',
        prompt: 'deg P = deg Q + 1 thường dẫn tới…',
        kind: 'choice',
        answer: 'tiệm cận xiên',
        choices: ['y=0', 'tiệm cận xiên', 'không có TC', 'chỉ TC đứng'],
        explanation: 'Chia đa thức được y=mx+c + phần dư/mẫu.',
      },
    ],
    tags: ['hữu tỉ', 'tiệm cận', 'khảo sát', 'lớp 12'],
  },
  {
    id: 'g12.stat.descriptive',
    version: '1.0.0',
    grade: 12,
    strand: 'statistics',
    topicCode: 'g12.statistics.descriptive',
    title: 'Thống kê mô tả: mẫu, ghép nhóm, ngoại lệ',
    subtitle: 'Mean, median, IQR, $s^2$, histogram, kéo điểm và so ghép nhóm',
    kind: 'exploration-lab',
    template: 'statistics-lab',
    dims: '2d',
    status: 'published',
    steps: 5,
    learningOutcomes: [
      'Tính và giải thích mean, median, mode, tứ phân vị',
      'Tính phương sai mẫu và độ lệch chuẩn',
      'Nhận ngoại lệ theo quy tắc 1.5×IQR',
      'Lập bảng tần số ghép nhóm và so mean ghép nhóm với mean thô',
    ],
    prerequisites: ['Trung bình, tần số', 'Căn bậc hai'],
    predictPrompt: 'Thêm một giá trị rất lớn vào mẫu — mean hay median lệch mạnh hơn?',
    checkpoints: [
      {
        id: 'stat-mean-med',
        prompt: 'Ngoại lệ lớn thường ảnh hưởng…',
        kind: 'choice',
        answer: 'mean nhiều hơn median',
        choices: ['median nhiều hơn mean', 'mean nhiều hơn median', 'IQR nhiều nhất', 'mode luôn đổi'],
        explanation: 'Mean dùng mọi giá trị; median chỉ thứ tự.',
      },
      {
        id: 'stat-var',
        prompt: 'Phương sai mẫu s² thường chia cho…',
        kind: 'choice',
        answer: 'n − 1',
        choices: ['n', 'n − 1', 'n + 1', '2n'],
        explanation: 'Hiệu chỉnh Bessel cho ước lượng không thiên vị.',
      },
      {
        id: 'stat-outlier',
        prompt: 'Hàng rào ngoại lệ phổ biến:',
        kind: 'choice',
        answer: 'Q1 − 1.5·IQR và Q3 + 1.5·IQR',
        choices: [
          'mean ± s',
          'Q1 − 1.5·IQR và Q3 + 1.5·IQR',
          'min và max',
          'median ± IQR',
        ],
        explanation: 'Quy tắc Tukey 1.5×IQR.',
      },
    ],
    tags: ['thống kê', 'histogram', 'phương sai', 'lớp 12'],
  },
  {
    id: 'g12.integral.cross-section',
    version: '1.1.0',
    grade: 12,
    strand: 'calculus',
    topicCode: 'g12.calc.integral',
    title: 'Thể tích theo thiết diện song song',
    subtitle: '$V=\\int S(x)\\,dx$ với lát vuông, tròn, tam giác hoặc chữ nhật',
    kind: 'process-simulation',
    template: 'cross-section',
    dims: 'hybrid',
    status: 'published',
    steps: 4,
    learningOutcomes: [
      'Viết S(x) theo dạng lát cắt',
      'Xấp xỉ thể tích bằng tổng lát mỏng',
      'Liên hệ với tích phân ∫S',
    ],
    prerequisites: ['Tích phân', 'Diện tích đa giác/tròn'],
    predictPrompt: 'Lát cắt vuông cạnh s(x) thì S(x) bằng gì?',
    checkpoints: [
      {
        id: 'cross-square',
        prompt: 'Vuông cạnh s(x) có diện tích…',
        kind: 'choice',
        answer: '[s(x)]²',
        choices: ['s(x)', '[s(x)]²', 'π[s(x)]²', 's/2'],
        explanation: 'S=a².',
      },
      {
        id: 'cross-circle',
        prompt: 'Lát tròn đường kính s(x) có…',
        kind: 'choice',
        answer: 'π[s(x)/2]²',
        choices: ['π[s]²', 'π[s(x)/2]²', 's²', '2πs'],
        explanation: 'Bán kính s/2.',
      },
    ],
    tags: ['thiết diện', 'thể tích', 'lớp 12'],
  },

  // ─── Lớp 12: Hình học tọa độ ─────────────────────────────────────
  {
    id: 'g12.geom.space-coords',
    version: '1.0.0',
    grade: 12,
    strand: 'geometry',
    topicCode: 'g12.geometry.space-coords',
    title: 'Tọa độ Oxyz: đường, mặt phẳng, mặt cầu',
    subtitle: '3D tương tác: khoảng cách, góc, giao mặt phẳng–mặt cầu và vị trí điểm',
    kind: 'process-simulation',
    template: 'space-coords',
    dims: '3d',
    status: 'published',
    steps: 6,
    learningOutcomes: [
      'Viết PT tham số đường thẳng và PT mặt phẳng',
      'Viết PT mặt cầu; phân loại điểm so với cầu',
      'Tính d(điểm, mp) và d(I, mp)',
      'Phân loại mp ∩ cầu: không giao / tiếp / cắt (đường tròn)',
      'Tính góc giữa đường thẳng và mặt phẳng',
    ],
    prerequisites: ['Vectơ trong không gian', 'Tích vô hướng'],
    predictPrompt: 'Khi d(I, mp) < R, giao của mặt phẳng và mặt cầu là hình gì?',
    checkpoints: [
      {
        id: 'space-plane',
        prompt: 'Mặt phẳng với pháp tuyến n qua P có dạng…',
        kind: 'choice',
        answer: 'n · (M − P) = 0',
        choices: ['n × (M−P)=0', 'n · (M − P) = 0', '|M−P|=R', 'M = P + t n'],
        explanation: 'Mọi vector trong mp vuông góc pháp tuyến.',
      },
      {
        id: 'space-sphere-cut',
        prompt: 'd(I,mp) < R thì mp và cầu…',
        kind: 'choice',
        answer: 'cắt nhau theo đường tròn',
        choices: ['không giao', 'tiếp xúc một điểm', 'cắt nhau theo đường tròn', 'trùng nhau'],
        explanation: 'Bán kính giao r = √(R²−d²).',
      },
      {
        id: 'space-angle',
        prompt: 'sinθ (góc đường–mp) bằng…',
        kind: 'choice',
        answer: '|u·n| / (|u||n|)',
        choices: ['|u·n| / (|u||n|)', 'u·n', '|u×n|', '1'],
        explanation: 'θ góc đường–mp: sinθ = |cos(góc u, n)|.',
      },
    ],
    tags: ['Oxyz', 'mặt cầu', 'mặt phẳng', '3D', 'lớp 12'],
  },

  // ─── Lớp 12: Xác suất ────────────────────────────────────────────
  {
    id: 'g12.prob.bayes',
    version: '1.0.0',
    grade: 12,
    strand: 'probability',
    topicCode: 'g12.probability.bayes',
    title: 'Xác suất có điều kiện và định lý Bayes',
    subtitle: 'Cây xác suất, bảng 1000 người, TP/FP và PPV',
    kind: 'exploration-lab',
    template: 'bayes-lab',
    dims: '2d',
    status: 'published',
    steps: 5,
    learningOutcomes: [
      'Phân biệt $P(+|B)$ và $P(B|+)$',
      'Dùng xác suất toàn phần tính $P(+)$',
      'Áp dụng Bayes; đọc PPV từ $\\dfrac{TP}{TP+FP}$',
      'Nhận ra vai trò của prior khi bệnh hiếm',
    ],
    prerequisites: ['Xác suất có điều kiện', 'Công thức nhân'],
    predictPrompt: 'Bệnh 1%, độ nhạy 99%, độ đặc hiệu 95%. Dương tính thì $P(B|+)$ khoảng bao nhiêu?',
    checkpoints: [
      {
        id: 'bayes-swap',
        prompt: 'P(+|B) và P(B|+)…',
        kind: 'choice',
        answer: 'nói chung khác nhau',
        choices: ['luôn bằng nhau', 'nói chung khác nhau', 'tổng bằng 1', 'không xác định'],
        explanation: 'Đó là hai điều kiện ngược chiều; Bayes chuyển từ cái này sang cái kia.',
      },
      {
        id: 'bayes-ppv',
        prompt: 'P(B|+) xấp xỉ trên bảng đếm bằng…',
        kind: 'choice',
        answer: 'TP / (TP + FP)',
        choices: ['TP/population', 'TP / (TP + FP)', 'độ nhạy', 'độ đặc hiệu'],
        explanation: 'Trong nhóm dương tính, tỉ lệ bệnh thật là TP/(TP+FP).',
      },
      {
        id: 'bayes-rare',
        prompt: 'Bệnh rất hiếm, xét nghiệm tốt — P(B|+) thường…',
        kind: 'choice',
        answer: 'thấp hơn trực giác (do FP)',
        choices: [
          'gần 100%',
          'thấp hơn trực giác (do FP)',
          'bằng độ nhạy',
          'bằng prior',
        ],
        explanation: 'Dương tính giả từ đa số người khỏe có thể át dương tính thật.',
      },
    ],
    tags: ['Bayes', 'xác suất', 'PPV', 'lớp 12'],
  },

  // ─── Lớp 11 (dày) ────────────────────────────────────────────────
  {
    id: 'g11.trig.unit-circle',
    version: '1.2.0',
    grade: 11,
    strand: 'trigonometry',
    topicCode: 'g11.trig.unit-circle',
    title: 'Đường tròn lượng giác và đồ thị sóng',
    subtitle: 'Đường tròn đơn vị, $\\sin$, $\\cos$, $\\tan$, $\\cot$, biên độ và pha',
    kind: 'interactive-model',
    template: 'unit-circle-trig',
    dims: '2d',
    status: 'published',
    steps: 1,
    learningOutcomes: [
      'Đọc sin, cos trên đường tròn đơn vị',
      'Liên hệ góc với đồ thị sóng',
      'Nhận tiệm cận tan/cot; thay A, B, φ',
    ],
    prerequisites: ['Góc và radian'],
    predictPrompt: '$\\sin$ hoàn thành mấy chu kỳ trên $[0,2\\pi]$?',
    checkpoints: [
      {
        id: 'trig-sin-cos-point',
        prompt: 'Điểm góc θ trên đường tròn đơn vị:',
        kind: 'choice',
        answer: '(cos θ, sin θ)',
        choices: ['(sin θ, cos θ)', '(cos θ, sin θ)', '(tan θ, cot θ)', '(θ, sin θ)'],
        explanation: 'x=cosθ, y=sinθ.',
      },
      {
        id: 'trig-period-sin',
        prompt: 'Chu kỳ cơ bản của sin:',
        kind: 'choice',
        answer: '2π',
        choices: ['π/2', 'π', '2π', '4π'],
        explanation: 'sin(θ+2π)=sinθ.',
      },
    ],
    tags: ['lượng giác', 'lớp 11'],
  },
  {
    id: 'g11.trig.equations',
    version: '1.0.0',
    grade: 11,
    strand: 'trigonometry',
    topicCode: 'g11.trig.equations',
    title: 'Phương trình lượng giác $\\sin x$, $\\cos x$, $\\tan x$',
    subtitle: 'Nghiệm trên đường tròn + đồ thị + họ nghiệm tổng quát',
    kind: 'process-simulation',
    template: 'trig-equations',
    dims: '2d',
    status: 'published',
    steps: 5,
    learningOutcomes: [
      'Giải sin x = m, cos x = m, tan x = m',
      'Biểu diễn nghiệm trên đường tròn và đồ thị',
      'Viết họ nghiệm tổng quát',
      'Đếm số nghiệm trên một đoạn',
    ],
    prerequisites: ['Đường tròn lượng giác', 'Hàm sin cos tan'],
    predictPrompt: 'sin x = 2 có bao nhiêu nghiệm thực?',
    checkpoints: [
      {
        id: 'trig-eq-domain',
        prompt: 'sin x = m vô nghiệm khi…',
        kind: 'choice',
        answer: '|m| > 1',
        choices: ['m = 0', '|m| > 1', 'm = 1', 'm < 0'],
        explanation: 'Tập giá trị sin là [−1;1].',
      },
      {
        id: 'trig-eq-tan',
        prompt: 'Họ nghiệm tan x = m:',
        kind: 'choice',
        answer: 'x = arctan m + kπ',
        choices: ['x = arctan m + 2kπ', 'x = arctan m + kπ', 'x = ±arctan m', 'vô nghiệm nếu m<0'],
        explanation: 'Chu kỳ tan là π.',
      },
      {
        id: 'trig-eq-cos',
        prompt: 'cos x = m (|m|≤1) có dạng…',
        kind: 'choice',
        answer: 'x = ±α + 2kπ',
        choices: ['x = α + kπ', 'x = ±α + 2kπ', 'x = (−1)^k α', 'chỉ một nghiệm'],
        explanation: 'α = arccos m.',
      },
    ],
    tags: ['phương trình lượng giác', 'lớp 11'],
  },
  {
    id: 'g11.calc.limits-continuity',
    version: '1.0.0',
    grade: 11,
    strand: 'calculus',
    topicCode: 'g11.calc.limits',
    title: 'Giới hạn và tính liên tục',
    subtitle: 'Bảng $h\\to0$, giới hạn trái/phải, hố, nhảy và gán $f(a)=L$',
    kind: 'process-simulation',
    template: 'limits-continuity',
    dims: '2d',
    status: 'published',
    steps: 6,
    learningOutcomes: [
      'Ước lượng lim bằng bảng giá trị hai phía',
      'So sánh lim trái và lim phải',
      'Phân loại liên tục / gián đoạn khử / nhảy / vô hạn',
      'Khử gián đoạn điểm bằng gán f(a)=L',
    ],
    prerequisites: ['Hàm số', 'Giá trị hàm'],
    predictPrompt: '$\\dfrac{x^2-1}{x-1}$ tại $x=1$ liên tục hay gián đoạn? Loại nào?',
    checkpoints: [
      {
        id: 'lim-two-sided',
        prompt: 'lim_{x→a} f tồn tại hữu hạn khi…',
        kind: 'choice',
        answer: 'lim trái = lim phải (hữu hạn)',
        choices: [
          'f(a) tồn tại',
          'lim trái = lim phải (hữu hạn)',
          'f liên tục trên ℝ',
          'f′(a) tồn tại',
        ],
        explanation: 'Định nghĩa hai phía.',
      },
      {
        id: 'lim-cont',
        prompt: 'f liên tục tại a khi…',
        kind: 'choice',
        answer: 'lim f(a) = f(a) (và cả hai tồn tại)',
        choices: [
          'chỉ cần f(a) có',
          'lim f(a) = f(a) (và cả hai tồn tại)',
          'f′(a)=0',
          'f không đổi dấu',
        ],
        explanation: 'Ba điều kiện: f(a), lim, bằng nhau.',
      },
      {
        id: 'lim-hole',
        prompt: 'lim có, f(a) sai/không có → thường là…',
        kind: 'choice',
        answer: 'gián đoạn khử được',
        choices: ['liên tục', 'gián đoạn khử được', 'gián đoạn nhảy', 'đạo hàm'],
        explanation: 'Gán f(a)=L để khử.',
      },
    ],
    tags: ['giới hạn', 'liên tục', 'lớp 11'],
  },
  {
    id: 'g11.calc.sequences',
    version: '1.0.0',
    grade: 11,
    strand: 'calculus',
    topicCode: 'g11.calc.sequences',
    title: 'Dãy số, CSC, CSN và lãi kép',
    subtitle: 'Bảng $u_n$, tổng $S_n$, công thức đóng, biểu đồ và truy hồi',
    kind: 'process-simulation',
    template: 'sequences-lab',
    dims: '2d',
    status: 'published',
    steps: 5,
    learningOutcomes: [
      'Phân biệt CSC và CSN; viết u_n, S_n',
      'Tính tổng bằng công thức và cộng dồn',
      'Mô hình lãi kép như CSN',
      'Quan sát hội tụ khi |q|<1',
    ],
    prerequisites: ['Lũy thừa', 'Tổng hữu hạn'],
    predictPrompt: 'CSC với d>0: đồ thị u_n theo n có dạng gì?',
    checkpoints: [
      {
        id: 'seq-csc',
        prompt: 'Số hạng tổng quát CSC:',
        kind: 'choice',
        answer: 'u_n = u_1 + (n−1)d',
        choices: ['u_n = u_1 q^{n−1}', 'u_n = u_1 + (n−1)d', 'u_n = n d', 'u_n = u_1^n'],
        explanation: 'Cộng d mỗi bước.',
      },
      {
        id: 'seq-csn-sum',
        prompt: 'S_n CSN (q≠1):',
        kind: 'choice',
        answer: 'u_1 (1−q^n)/(1−q)',
        choices: ['n u_1', 'u_1 (1−q^n)/(1−q)', 'u_1 q^n', '(u_1+u_n)/2'],
        explanation: 'Công thức cấp số nhân.',
      },
      {
        id: 'seq-compound',
        prompt: 'Lãi kép A_n = A_0(1+i)^n là…',
        kind: 'choice',
        answer: 'CSN với q = 1+i',
        choices: ['CSC', 'CSN với q = 1+i', 'dãy truy hồi bất kỳ', 'không phải dãy'],
        explanation: 'Mỗi năm nhân (1+i).',
      },
    ],
    tags: ['dãy số', 'CSC', 'CSN', 'lãi kép', 'lớp 11'],
  },
  {
    id: 'g11.geom.space-relations',
    version: '1.0.0',
    grade: 11,
    strand: 'geometry',
    topicCode: 'g11.geometry.space',
    title: 'Hình không gian: song song và vuông góc',
    subtitle: 'Hai đường và đường–mặt phẳng qua $\\vec u\\cdot\\vec v$, $\\vec u\\times\\vec v$, $\\vec u\\cdot\\vec n$',
    kind: 'process-simulation',
    template: 'space-relations',
    dims: '3d',
    status: 'published',
    steps: 6,
    learningOutcomes: [
      'Nhận song song / vuông góc / chéo của hai đường',
      'Nhận đường ∥ / ⊥ / nằm trong mặt phẳng',
      'Dùng tích vô hướng và tích có hướng',
      'Tính góc đường–mp và khoảng cách điểm–mp',
    ],
    prerequisites: ['Vectơ', 'Tích vô hướng'],
    predictPrompt: 'u×v=0 và A,B không thẳng hàng trên một đường thì hai đường…',
    checkpoints: [
      {
        id: 'sp-par',
        prompt: 'Hai đường cùng phương khi…',
        kind: 'choice',
        answer: 'u × v = 0',
        choices: ['u · v = 0', 'u × v = 0', 'u = v bắt buộc', '|u|=|v|'],
        explanation: 'Tích có hướng triệt tiêu.',
      },
      {
        id: 'sp-perp',
        prompt: 'Hai đường vuông góc (chỉ phương) khi…',
        kind: 'choice',
        answer: 'u · v = 0',
        choices: ['u × v = 0', 'u · v = 0', 'cùng điểm', 'song song'],
        explanation: 'Tích vô hướng triệt tiêu.',
      },
      {
        id: 'sp-plane',
        prompt: 'Đường ∥ mặt phẳng khi…',
        kind: 'choice',
        answer: 'u · n = 0',
        choices: ['u · n = 0', 'u × n = 0', 'A thuộc mp', 'n = 0'],
        explanation: 'Chỉ phương vuông góc pháp tuyến.',
      },
    ],
    tags: ['hình không gian', 'song song', 'vuông góc', 'lớp 11'],
  },
  {
    id: 'g11.prob.tree',
    version: '1.0.0',
    grade: 11,
    strand: 'probability',
    topicCode: 'g11.probability.rules',
    title: 'Cây xác suất và quy tắc nhân',
    subtitle: 'Hai tầng, $P(A\\cap B)$, xác suất toàn phần, hợp và độc lập',
    kind: 'exploration-lab',
    template: 'probability-tree-g11',
    dims: '2d',
    status: 'published',
    steps: 5,
    learningOutcomes: [
      'Dựng cây 2 tầng với xác suất có điều kiện',
      'Tính P(A∩B) bằng quy tắc nhân',
      'Tính P(B) bằng công thức toàn phần',
      'Nhận biết độc lập; tính P(A∪B)',
    ],
    prerequisites: ['Xác suất cơ bản', 'Biến cố'],
    predictPrompt: 'Nếu P(B|A)=P(B|Ā) thì A và B có độc lập không?',
    checkpoints: [
      {
        id: 'prob-mult',
        prompt: 'P(A∩B) khi biết P(B|A):',
        kind: 'choice',
        answer: 'P(A)·P(B|A)',
        choices: ['P(A)+P(B)', 'P(A)·P(B|A)', 'P(A)/P(B)', 'P(B|A)−P(A)'],
        explanation: 'Quy tắc nhân.',
      },
      {
        id: 'prob-total',
        prompt: 'P(B) với phân hoạch A, Ā:',
        kind: 'choice',
        answer: 'P(B|A)P(A)+P(B|Ā)P(Ā)',
        choices: [
          'P(B|A)+P(B|Ā)',
          'P(B|A)P(A)+P(B|Ā)P(Ā)',
          'P(A∩B)',
          'P(A∪B)',
        ],
        explanation: 'Xác suất toàn phần.',
      },
      {
        id: 'prob-indep',
        prompt: 'A, B độc lập khi…',
        kind: 'choice',
        answer: 'P(B|A) = P(B)',
        choices: ['P(A)=P(B)', 'P(B|A) = P(B)', 'P(A∪B)=1', 'P(A∩B)=0'],
        explanation: 'Hoặc P(A∩B)=P(A)P(B).',
      },
    ],
    tags: ['xác suất', 'cây', 'độc lập', 'lớp 11'],
  },
];

export function getSimulation(id: string): SimulationSpec | undefined {
  const raw = SIMULATIONS.find((item) => item.id === id);
  return raw ? applyG12ToolTrip(raw) : undefined;
}

export function listSimulations(filter?: {
  grade?: number | 'all';
  strand?: string | 'all';
  query?: string;
  status?: 'all' | 'published' | 'draft';
}): SimulationSpec[] {
  const grade = filter?.grade ?? 'all';
  const strand = filter?.strand ?? 'all';
  const query = (filter?.query ?? '').trim().toLowerCase();
  const status = filter?.status ?? 'all';

  return SIMULATIONS.filter((item) => {
    if (grade !== 'all' && item.grade !== grade) return false;
    if (strand !== 'all' && item.strand !== strand) return false;
    if (status !== 'all' && item.status !== status) return false;
    if (!query) return true;
    const hay = [item.title, item.subtitle, item.topicCode, ...item.tags, ...item.learningOutcomes].join(' ').toLowerCase();
    return hay.includes(query);
  })
    .map(applyG12ToolTrip)
    .sort((a, b) => b.grade - a.grade || a.title.localeCompare(b.title, 'vi'));
}
