from app.services.prompts.nlp import (
    NLP_CONTRACT_VERSION,
    NLP_CRITIC_PROMPT_VERSION,
    NLP_CRITIC_SYSTEM_PROMPT,
    NLP_INTERPRETATION_PROMPT_VERSION,
    NLP_INTERPRETATION_SYSTEM_PROMPT,
)

__all__ = [
    "NLP_CONTRACT_VERSION",
    "NLP_CRITIC_PROMPT_VERSION",
    "NLP_CRITIC_SYSTEM_PROMPT",
    "NLP_INTERPRETATION_PROMPT_VERSION",
    "NLP_INTERPRETATION_SYSTEM_PROMPT",
]